theme: jekyll-theme-cayman
title: PH 310 Research Project - Theories of Knowledge and Learning in the 18th century 
description: This website was built for a research project for one of my philosophy classes, PH 310 - History of Modern Philosophy. 
             Tasked with using data to answer a question we come up with ourselves, I was inspired by kant's views on knowledge 
             and will attempt to create a picture of how common such theories were in the 18th century 